import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={clsx(
					inter.className,
					" max-w-7xl mx-auto overflow-y-scroll"
				)}
			>
				<nav className="w-[350px] fixed min-h-screen bg-slate-100">
					<Sidebar />
				</nav>

				<main className="ml-[350px]">{children}</main>
			</body>
		</html>
	);
}
